<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Shared.csproj" />
    <ProjectReference Include="..\DirectoryService.Contracts\DirectoryService.Contracts.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" />
    <PackageReference Include="TimeZoneConverter" />
  </ItemGroup>

</Project>
